config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  get '/welcome', to: 'welcome#index', as: 'welcome'
  get 'users_search', to: 'users#search', as: 'users_search'
  get 'users_selection', to:'users#selection', as:'users_selection'
  get 'users_display', to: 'users#display', as:'users_display'

  devise_for :users, :controllers => {:registrations => "user/registrations"} 
  resources :users, except: [:new, :create]
  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end
  resources :chatrooms, only: [:index, :create, :show] do
    resources :messages, only: [:create]
  end

  get '*unmatched_route', to: 'application#raise_not_found', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar

  after_create :welcome_send

  
  has_many :chatrooms_as_user1, class_name: 'Chatroom', foreign_key: 'user1_id', dependent: :destroy
  has_many :chatrooms_as_user2, class_name: 'Chatroom', foreign_key: 'user2_id', dependent: :destroy
  has_many :sent_messages, class_name: 'Message', foreign_key: 'sender_id', dependent: :destroy
  has_many :received_messages, class_name: 'Message', foreign_key: 'receiver_id', dependent: :destroy

  
  enum experience: { 
    'Débutant': 1, 
    '40': 2, 
    '30/5': 3, 
    '30/4': 4, 
    '30/3': 5, 
    '30/2': 6, 
    '30/1': 7, 
    '30': 8, 
    '15/5': 9, 
    '15/4': 10, 
    '15/3': 11, 
    '15/2': 12, 
    '15/1': 13, 
    '15': 14, 
    '5/6': 15, 
    '4/6': 16,
    '3/6': 17,
    '2/6': 18,
    '1/6': 19,
    '0': 20,
    '-2/6': 21,
    '-4/6': 22,
    '-15': 23,
    '-30': 24
  }
  enum gender: { Femme: 1, Homme: 2, Autre: 3 }

  def age
    if date_of_birth.present?
    (Date.today - date_of_birth).to_i / 365
    end
  end

  def welcome_send
    UserMailer.welcome_email(self).deliver_now!
  end

  def chatrooms
    chatrooms_as_user1.or(chatrooms_as_user2)
  end

  def self.search(partner_params, user)
    @partners = User.where.not(id: user.id)

    case partner_params[:gender]
    when "Femme"
      @partners = @partners.select{|partner| (partner.gender == "Femme")|| (partner.gender == "Autre" ) }
    when "Homme"
      @partners = @partners.select{|partner| (partner.gender == "Homme")|| (partner.gender == "Autre" ) }
    else
      @partners = @partners.select{|partner| (partner.gender == "Homme")|| (partner.gender == "Autre" ) || (partner.gender == "Femme" ) }
    end
    
    if partner_params[:week_day]== "1" || partner_params[:week_night]== "1" || partner_params[:weekend_day]== "1" || partner_params[:weekend_night]== "1"
      disponibilities = []
      disponibilities << :week_day if partner_params[:week_day]== "1"
      disponibilities << :week_night if partner_params[:week_night]== "1"
      disponibilities << :weekend_day if partner_params[:weekend_day]== "1" 
      disponibilities << :weekend_night if partner_params[:weekend_night]== "1"
      
      @partners = @partners.select do |partner|
        disponibilities.any? { |disponibility| partner[disponibility] }
      end

    end

    if partner_params[:inside] == "1"
      @partners = @partners.select{|partner| (partner.outside === false)}
    end

    @partners = User.filter_level(@partners,user)

    return @partners
  end


  def self.filter_level(partner,user)
    @partners = partner
    @partners = @partners.select do |partner|
      if user.gender == "Homme"
        if partner.gender == "Homme"
          partner.experience_before_type_cast >= (user.experience_before_type_cast - 3) && partner.experience_before_type_cast <= (user.experience_before_type_cast + 3)
        elsif partner.gender == "Femme" 
          partner.experience_before_type_cast >= user.experience_before_type_cast && partner.experience_before_type_cast <= (user.experience_before_type_cast + 4)
        else
          partner.experience_before_type_cast >= (user.experience_before_type_cast - 4) && partner.experience_before_type_cast <= (user.experience_before_type_cast + 4)
        end
      elsif user.gender == "Femme"
        if partner.gender == "Femme"
          partner.experience_before_type_cast >= (user.experience_before_type_cast - 3) && partner.experience_before_type_cast <= (user.experience_before_type_cast + 3)
        elsif partner.gender == "Homme" 
          partner.experience_before_type_cast >= (user.experience_before_type_cast - 4) && partner.experience_before_type_cast <= user.experience_before_type_cast
        else
          partner.experience_before_type_cast >= (user.experience_before_type_cast - 4) && partner.experience_before_type_cast <= (user.experience_before_type_cast + 4)
        end
      else
        partner.experience_before_type_cast >= (user.experience_before_type_cast - 4) && partner.experience_before_type_cast <= (user.experience_before_type_cast + 4)
      end
    end

    return @partners
  end

  
  def has_chatroom_with?(other_user)
    Chatroom.where(user1_id: [self.id, other_user.id], user2_id: [self.id, other_user.id]).exists?
  end

  def common_chatroom_id_with(other_user)
    Chatroom.where(user1: self, user2: other_user).or(Chatroom.where(user1: other_user, user2: self)).first
  end

  def messages
    sent_messages.or(received_messages)
  end

  def self.ransackable_attributes(auth_object = nil)
    %w(last_name first_name experience)
  end

  def self.ransackable_associations(auth_object = nil)
    %w(first_name_or_last_name)
  end


end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  layout 'visitor'
  
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?

  layout 'visitor'
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
   def create
    if params[:user][:code_club] != "tcstjulien74"
      flash[:alert] = "Votre code club/numéro de licence n'est pas valide"
      redirect_to new_user_registration_path
      return
    end
  
    super
   end

  # GET /resource/edit
  def edit
    render layout: 'layouts/user_actions'
  end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def after_update_path_for(resource)
    edit_user_registration_path
  end

    # The path used after sign up.
  def after_sign_up_path_for(resource)
    flash[:notice] = "Bienvenue au TC St Julien, #{current_user.first_name.capitalize} ! Tu peux modifier tes préférences de jeu par ici."
    edit_user_path(current_user.id)
  end

  # If you have extra params to permit, append them to the sanitizer.
  

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute, :code_club])
  # end



  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController

  layout 'visitor'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  layout 'user_default'


  # GET /users or /users.json
  def index
    @partners = User.where.not(id: current_user.id)
    @q = @partners.ransack(params[:q])
    @partners = @q.result(distinct: true)
  end
  
  # GET /users/1 or /users/1.json
  def show
    if current_user != @user
      if current_user.has_chatroom_with?(@user)
        @have_chatroom = true
        @chatroom = current_user.common_chatroom_id_with(@user)
      else
        @have_chatroom = false
        @chatroom = Chatroom.new
      end
    end
    render layout: 'layouts/user_actions'
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    render layout: 'layouts/user_actions'
  end

  def search
    render layout: 'layouts/user_actions'
  end

  def selection
    @user = current_user
    @partners = User.search(partner_params, @user)

    if @partners.empty?
      flash[:filter] = "Aucun joueur de ton niveau n'est disponible sur ce créneau. Voici des joueurs disponibles à d'autres moments !"
      @partners = User.where.not(id: @user.id)
      @partners = User.filter_level(@partners, @user)

      if @partners.empty?
        flash[:filter] = "Il n'y a malheureusement aucun joueur de ton niveau inscrit sur notre site. Voici la liste complète des joueurs."
        @partners = User.where.not(id: @user.id)
      end
    end

    redirect_to users_display_path(:partners => @partners)
  end

  def display
    results = params[:partners]
    @partners = []
    if results
      results.each do |result|
        iresult = result.to_i
        @partners << User.find(iresult)
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_path(@user), success: "Modifications enregistrées." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, success: "Le compte a bien été supprimé." }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :code_club, :date_of_birth, :gender, :experience, :description, :week_day, :week_night, :weekend_day, :weekend_night, :outside)
    end

    def partner_params
      params.permit(:gender, :week_day, :week_night, :weekend_day, :weekend_night, :inside, :authenticity_token, :commit, :method)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_list_item.html.erb
<li>
  <%= link_to user_path(partner.id), class: "container" do %>
    <% if partner.avatar.attached? %>
      <%= image_tag partner.avatar, alt: 'Photo de profil', class: "avatar" %>
    <% else %>
      <div class="avatar-placeholder">
        <i class="bi bi-person-circle"></i>
      </div>
    <% end %>
    
    <div class="infos">
      <div class="header">
        <h2><%= partner.first_name %> <%= partner.last_name %></h2>
      </div>
      <small><%= "#{partner.experience}" if partner.experience -%><%= ", " if partner.age && partner.experience -%><%= "#{partner.age} ans" if partner.age %></small>
    </div>
  <% end %>
</li>

app/views/users/display.html.erb
<% content_for :title do %>
  <h1 class="title">Membres trouvés</h1>
<% end %>

<div class="container container-m">
  <div class="alert alert-filter" role="alert">
    <p><i class="bi bi-info-circle-fill"></i>Les membres affichés sont <strong>automatiquement filtrés selon votre niveau de jeu</strong>.</p>
  </div>
</div>

<div class="stack-buttons">
  <%= link_to users_search_path, class: "btn btn-outline-primary" do %>
    <i class="bi bi-filter"></i>
    Filtrer à nouveau
  <% end %>
  <%= link_to users_path, class: "btn btn-outline-primary" do %>
    Afficher tous les membres
  <% end %>
</div>

<ul class="users">
  <% @partners.each do |partner| %>
    <%= render "list_item", partner: partner %>
  <% end %>
</ul>

app/views/users/edit.html.erb
<% content_for :back_button do %>
  <%= link_to user_path(current_user), class: "btn-back" do %>
    <i class="bi bi-arrow-left"></i>
  <% end %>
<% end %>

<% content_for :title do %>
  <h1 class="title">Éditer mon profil</h1>
<% end %>

<div class="container-xl profile">

  <%= form_tag user_avatars_path(@user), multipart: true, class: "stack" do %>
    <h2>Choisissez votre photo de profil</h2>
    <%= file_field_tag :avatar, class: "form-control" %>
    <%= submit_tag "Enregistrer", class: "btn btn-outline-primary" %>
  <% end %>

  <%= form_with model: @user, local: true, :id => "edit_user", html: { class: "stack" } do |f| %>
    <hr>
    <div>
      <h2>Votre niveau de jeu</h2>
      <%= f.select :experience, User.experiences.keys, {}, { :class => "form-select" } %>
    </div>
    <hr>
    <div>
      <h2>Vos disponibilités</h2>
      <div class="form-check form-switch">
        <%= f.check_box :week_day, class: "form-check-input", role: "switch" %>
        <%= f.label :week_day, "La semaine, en journée", class: "form-check-label" %>
      </div>
      <div class="form-check form-switch">
        <%= f.check_box :week_night, class: "form-check-input", role: "switch" %>
        <%= f.label :week_night, "La semaine, en soirée", class: "form-check-label" %>
      </div>
      <div class="form-check form-switch">
        <%= f.check_box :weekend_day, class: "form-check-input", role: "switch" %>
        <%= f.label :weekend_day, "Le week-end, en journée", class: "form-check-label" %>
      </div>
      <div class="form-check form-switch">
        <%= f.check_box :weekend_night, class: "form-check-input", role: "switch" %>
        <%= f.label :weekend_night, "Le week-end, en soirée", class: "form-check-label" %>
      </div>
    </div>
    <hr>
    <div>
      <h2>Préférence de terrain</h2>
      <div class="form-check form-switch">
        <%= f.check_box :outside, class: "form-check-input", role: "switch" %>
        <%= f.label :outside, "Je joue seulement outdoor.", class: "form-check-label" %>
      </div>
    </div>
    <hr>
    <div>
      <h2>À propos de vous</h2>
      <%= f.text_area :description, rows: 5, class: "form-control", placeholder: "Vous préférez le dur ou la terre battue ? Vous devez jongler avec la saison de ski ou avec les emplois du temps de vos enfants ? Partagez ces informations ici !" %>
      <div>
        <%= f.label :first_name, "Votre prénom", class: "form-label" %>
        <%= f.text_field :first_name, class: "form-control" %>
      </div>
      <div>
        <%= f.label :last_name, "Votre nom", class: "form-label" %>
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
      <div>
        <%= f.label :date_of_birth, "Votre date de naissance", class: "form-label" %>
        <%= f.date_field :date_of_birth, class: "form-control" %>
      </div>
      <div>
        <%= f.label :genre, "Votre genre", class: "form-label" %>
        <%= f.select :gender, User.genders.keys, {}, { :class => "form-select" } %>
      </div>
    </div>
  <% end %>
</div>

<% content_for :actions do %>
  <%= button_tag type: :submit, :form => "edit_user", class: "btn btn-primary" do %>
    <span class="icon icon-check"></span>
    Enregistrer les modifications
  <% end %>
<% end %>

app/views/users/index.html.erb
<% content_for :title do %>
  <h1 class="title">Membres du club</h1>
<% end %>

<div class="stack-buttons">
  <%= link_to users_search_path, class: "btn btn-outline-primary" do %>
    <i class="bi bi-filter"></i>
    Filtrer les membres
  <% end %>
  <%= search_form_for @q, remote: true, class: "input-search" do |f| %>
    <%= f.search_field :first_name_or_last_name_i_cont, placeholder: "Recherche par nom", class: "form-control" %>
    <%= f.button type: :submit, class: "btn btn-outline-primary" do %>
      <i class="bi bi-search"></i>
    <% end %>
  <% end %>
</div>

<ul class="users">
  <% @partners.each do |partner| %>
    <%= render "list_item", partner: partner %>
  <% end %>
</ul>

app/views/users/search.html.erb
<% content_for :back_button do %>
  <%= link_to root_path, class: "btn-back" do %>
    <i class="bi bi-arrow-left"></i>
  <% end %>
<% end %>

<% content_for :title do %>
  <h1 class="title">Filtres de recherche</h1>
<% end %>

<div class="container-xl">
  <%= form_with(url: users_selection_path, method: :get, class: "stack", :id => "search") do |f| %>
    <h2>Genre</h2>
    <div>
      <div class="form-check">
        <%= f.radio_button :gender, "Femme", { :class => "form-check-input", :role => "switch" } %>
        <%= f.label :gender_woman, "Femme", class: "form-check-label" %>
      </div>
      <div class="form-check">
        <%=  f.radio_button :gender, "Homme", { :class => "form-check-input", :role => "switch" } %>
        <%= f.label :gender_man, "Homme", class: "form-check-label" %>
      </div>
      <div class="form-check">
        <%=  f.radio_button :gender, "Peu importe", { :class => "form-check-input", :role => "switch" } %>
        <%= f.label :gender_whatever, "Peu importe", class: "form-check-label" %>
      </div>
    </div>
    <hr>
    <h2>Disponibilité</h2>
    <div>
      <div class="form-check form-switch">
      
        <%= f.check_box :week_day, class: "form-check-input", role: "switch" %>
        <%= f.label :week_day, "La semaine, en journée", class: "form-check-label" %>
      </div>
      <div class="form-check form-switch">
        <%= f.check_box :week_night, class: "form-check-input", role: "switch" %>
        <%= f.label :week_night, "La semaine, en soirée", class: "form-check-label" %>
      </div>
      <div class="form-check form-switch">
        <%= f.check_box :weekend_day, class: "form-check-input", role: "switch" %>
        <%= f.label :weekend_day, "Le week-end, en journée", class: "form-check-label" %>
      </div>
      <div class="form-check form-switch">
        <%= f.check_box :weekend_night, class: "form-check-input", role: "switch" %>
        <%= f.label :weekend_night, "Le week-end, en soirée", class: "form-check-label" %>
      </div>
    </div>
    <hr>
    <h2>Préférence de terrain</h2>
    <div>
      <div class="form-check form-switch">
        <%= f.check_box :inside, class: "form-check-input", role: "switch" %>
        <%= f.label :inside, "Je veux jouer en indoor", class: "form-check-label" %>
      </div>
    </div>
  <% end %>
</div>

<% content_for :actions do %>
  <%= button_tag type: :submit, :name => "commit", :form => "search", class: "btn btn-primary" do %>
    <i class="bi bi-search"></i>
    Appliquer les filtres
  <% end %>
<% end %>

app/views/users/show.html.erb
<% content_for :back_button do %>
  <%= link_to root_path, class: "btn-back" do %>
    <i class="bi bi-arrow-left"></i>
  <% end %>
<% end %>

<% content_for :title do %>
  <h1 class="title"><%= "Mon " if @user == current_user %>Profil</h1>
<% end %>

<div class="container-xl profile">
  <div class="header">
    <% if @user.avatar.attached? %>
      <%= image_tag @user.avatar, alt: 'Photo de profil', class: "avatar" %>
    <% else %>
      <div class="avatar-placeholder">
        <i class="bi bi-person-circle"></i>
      </div>
    <% end %>
    <div>
      <h2><%= @user.first_name %> <%= @user.last_name %></h2>
      <ul>
        <% if @user.description %><li><%= @user.experience %></li><% end %>
        <% unless @user.gender == "Autre" %><li><%= @user.gender %></li><% end %>
        <% if @user.age %><li><%= @user.age %> ans</li><% end %>
      </ul>
    </div>
  </div>

  <div>
    <% unless @user.description == '' %>
      <h3>À propos</h3>
      <p><%= @user.description %></p>
      <hr>
    <% end %>
    <% if @user.week_day || @user.week_night || @user.weekend_day || @user.weekend_night %>
      <h3>Je suis disponible</h3>
      <ul>
        <% if @user.week_day %><li>La semaine, en journée</li><% end %>
        <% if @user.week_night %><li>La semaine, en soirée</li><% end %>
        <% if @user.weekend_day %><li>Le week-end, en journée</li><% end %>
        <% if @user.weekend_night %><li>Le week-end, en soirée</li><% end %>
      </ul>
      <hr>
    <% end %>
    <h3>Préférence de terrain</h3>
    <% if @user.outside %>
      <p>Je joue outdoor uniquement.</p>
    <% else %>
      <p>Je joue indoor et outdoor.</p>
    <% end %>
    <hr>   
</div>

<% content_for :actions do %>

  <% if @user == current_user %>

    <%= link_to edit_user_path(current_user), class: "btn btn-primary" do %>
      <i class="bi bi-pencil-square"></i>
      Éditer mon profil
    <% end %>
    <div class="container">
      <%= link_to edit_user_registration_path, class: "btn btn-outline-primary" do %>
        <i class="bi bi-gear-fill"></i>
        Gérer mon compte
      <% end %>
      <%= button_to destroy_user_session_path, method: :delete, class: "btn btn-outline-primary" do %>
        <i class="bi bi-box-arrow-right"></i>
        Me déconnecter
      <% end %>
    </div>

  <% else %>

    <% if @have_chatroom %>

      <% if @chatroom.messages.present? %>
        <%= link_to chatroom_path(@chatroom), class: "btn btn-primary" do %>
          <i class="bi bi-chat-dots-fill"></i>
          Ouvrir la conversation
        <% end %>
      <% else %>
        <%= link_to chatroom_path(@chatroom), class: "btn btn-primary" do %>
          <i class="bi bi-chat-dots-fill"></i>
          Organiser une partie
        <% end %>
      <% end %>
      
    <% else %>
      
      <%= form_with(url: chatrooms_path, method: :post) do |f| %>
        <%= f.hidden_field :user_id, value: @user.id %>
        <%= f.button type: :submit, class: "btn btn-primary" do %>
          <i class="bi bi-chat-dots-fill"></i>
          Organiser une partie
        <% end %>
      <% end %>
      
    <% end %>

  <% end %>

<% end %>