config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  get '/welcome', to: 'welcome#index', as: 'welcome'
  get 'users_search', to: 'users#search', as: 'users_search'
  get 'users_selection', to:'users#selection', as:'users_selection'
  get 'users_display', to: 'users#display', as:'users_display'

  devise_for :users, :controllers => {:registrations => "user/registrations"} 
  resources :users, except: [:new, :create]
  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end
  resources :chatrooms, only: [:index, :create, :show] do
    resources :messages, only: [:create]
  end

  get '*unmatched_route', to: 'application#raise_not_found', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
end

app/views/layouts/_alerts.html.erb
<% flash.each do |type, content| %>
  <% type = 'success' if type == 'notice' %>
  <div class="container container-m">
    <div class="alert alert-<%= type %> container-m" role="alert">
      <% case type 
         when "info" %><i class="bi bi-info-circle-fill"></i>
      <% when "filter" %><i class="bi bi-info-circle-fill"></i>
      <% when "alert" %><i class="bi bi-exclamation-triangle-fill"></i>
      <% when "warning" %><i class="bi bi-exclamation-triangle-fill"></i>
      <% when "success" %><i class="bi bi-check-circle-fill"></i>
      <% end %>
      <%= content %>
    </div>
  </div>
<% end %>

app/views/layouts/_back_button.html.erb
<%= link_to url_for(:back), class: "btn-back" do %>
  <i class="bi bi-arrow-left"></i>
<% end %>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="container">
    <%= link_to users_path, class: "#{'active' if current_page?(root_path) || current_page?(users_search_path) || current_page?(users_path) || current_page?(users_display_path) }" do %>
      <i class="bi bi-people-fill"></i>
      <span>Membres</span>
    <% end %>
    <%= link_to chatrooms_path, class: "#{'active' if current_page? chatrooms_path }" do %>
      <i class="bi bi-chat-dots-fill"></i>
      <span>Messages</span>
    <% end %>
  </div>
  <%= link_to user_path(current_user), class: "#{'active' if current_page?(user_path(current_user)) || current_page?(edit_user_registration_path) || current_page?(edit_user_path(current_user)) }" do %>
    <% if current_user.avatar.attached? %>
      <%= image_tag current_user.avatar, alt: 'Photo de profil', class: "avatar" %>
    <% else %>
      <i class="bi bi-person-circle"></i>
    <% end %>
    <span>Mon profil</span>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr" data-theme="light">
  <head>
    <meta charset="utf-8">
    <title>Tennis Partner App</title>
    <link rel="icon" href="https://fav.farm/🎾" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@300;700&display=swap" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Varela+Round" %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

   <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.min.js", "integrity": "sha384-heAjqF+bCxXpCWLa6Zhcp4fu20XoNIA98ecBC1YkdXhszjoejr5y9Q77hIrv8R9i", "crossorigin": "anonymous", "defer": "defer", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= yield :javascript %>
  </head>

  <body>
    <%= yield :header %>
    <%= yield :main %>
    <%= yield :footer %>
  </body>
</html>

app/views/layouts/user_actions.html.erb
<% content_for :header do %>
  <header class="actions">
    <%= yield :back_button %>
    <%= yield :title %>
  </header>
<% end %>

<% content_for :main do %>
  <main>
    <%= render 'layouts/alerts' %>
    <%= yield %>
  </main>
<% end %>

<% content_for :footer do %>
  <footer class="actions">
    <%= yield :actions %>
  </footer>
<% end %>

<%= render template: "layouts/application" %>

app/views/layouts/user_chatroom.html.erb
<% content_for :header do %>
  <header class="actions">
    <%= yield :back_button %>
    <%= yield :title %>
  </header>
<% end %>

<% content_for :main do %>
  <main>
    <%= render 'layouts/alerts' %>
    <%= yield %>
  </main>
<% end %>

<% content_for :footer do %>
  <footer class="action-chatroom">
    <%= yield :action_chatroom %>
  </footer>
<% end %>

<%= render template: "layouts/application" %>

app/views/layouts/user_default.html.erb
<% content_for :header do %>
  <header class="default">
    <%= yield :title %>
  </header>
<% end %>

<% content_for :main do %>
  <main>
    <%= render 'layouts/alerts' %>
    <%= yield %>
  </main>
<% end %>

<% content_for :footer do %>
  <footer class="default">
    <%= render 'layouts/navbar' %>
  </footer>
<% end %>

<%= render template: "layouts/application" %>

app/views/layouts/visitor.html.erb
<% content_for :header do %>
  <header class="actions visitor">
    <%= yield :back_button %>
    <%= yield :title %>
  </header>
<% end %>

<% content_for :main do %>
  <main class="visitor">
    <%= yield %>
    <%= render 'layouts/alerts' %>
  </main>
<% end %>

<% content_for :footer do %>
  <footer class="actions visitor">
    <%= yield :actions %>
  </footer>
<% end %>

<%= render template: "layouts/application" %>